project_name: pg-activity-watchdog
builds:
  - goarch:
      - amd64
    env:
      - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    amd64: x86_64
